### ISSUE TITLE
Blinking test_datastore_reload

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-server-rust#101]
This has happened to me a couple of times now, only in macOS builds (that I can remember): https://travis-ci.org/github/ActivityWatch/activitywatch/jobs/665409298

```
---- datastore_tests::test_datastore_reload stdout ----

thread 'datastore_tests::test_datastore_reload' panicked at 'assertion failed: `(left == right)`

  left: `None`,

 right: `Some(2020-03-22T07:35:27.975762Z)`', aw-datastore/tests/datastore.rs:423:13

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I've been getting it with GitHub Actions as well, so not Travis-specific.

**Comment by xylix** [comment]
There was an issue already since I've had this on my dev machine and an ubuntu VM (iirc) https://github.com/ActivityWatch/aw-server-rust/issues/95

**Comment by ErikBjare** [comment]
Ah alright, closing.
