### ISSUE TITLE
Building cargo-kcov in CI takes >5min

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-server-rust#117]
Slowing down the build significantly: https://github.com/ActivityWatch/aw-server-rust/pull/89/checks?check_run_id=638369573

Running the tests themselves under coverage also take considerable time (>5min), but I noticed that just building cargo-kcov takes ~5min.

**Comment by johan-bjareholt** [comment]
The coverage is also completely broken, some files say that we for example have 133 lines not hit while the file is only 13 lines long...

**Comment by johan-bjareholt** [comment]
grcov is merged and working, closing
