### ISSUE TITLE
Deleting bucket in webui doesn't work 

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-server-rust#12]
At least not on Android, in the #11 PR.

**Comment by johan-bjareholt** [comment]
There are function tests for this which pass just fine (through the REST API and everything) so we need more info to understand what's going on.

**Comment by johan-bjareholt** [comment]
The function test was apparently partly commented out...
Fixed in https://github.com/ActivityWatch/aw-server-rust/commit/73e78114256e99de3c25bbbad9630b7d202e6376

**Comment by ErikBjare** [comment]
Works great now, thanks!
