### ISSUE TITLE
Safe CORS configuration

### ISSUE THREAD

**Issue by johan-bjareholt** [ActivityWatch/aw-server-rust#24]
[rocket_cors now support regex in the origin configuration](https://github.com/lawliet89/rocket_cors/pull/62), we should use that to implement CORS safely. Maybe also add support for custom origin configurations in the config?

**Comment by ErikBjare** [comment]
Some bad news: In Firefox, extensions do not use their ID in the extension URL, they use an installation-unique extension UUID (apparently to prevent fingerprinting).

They mention it here: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/web_accessible_resources

![image](https://user-images.githubusercontent.com/1405370/62939191-f606d180-bdd0-11e9-89a9-c9be395d0b14.png)
