### ISSUE TITLE
Broken with latest aw-webui (if audible-as-active is enabled, as is default)

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-server-rust#240]
Not sure what is going wrong here, but for some reason the audible-as-active thing silently breaks the query (no results).

![image](https://user-images.githubusercontent.com/1405370/119828659-ac7e6c80-befa-11eb-904a-6fca0ce6cdd9.png)

**Comment by johan-bjareholt** [comment]
Huh, interesting. I guess the easiest way to debug would be to write a simple query and then slowly incorporate all features the full query does. Then see where it stops working as expected.

**Comment by johan-bjareholt** [comment]
Fixed :)

**Comment by johan-bjareholt** [comment]
Before closing, please verify that it works as expected in the web-ui since I don't have any good data to test on.
I can see that some days the active time increases by a few minutes, but not much more.

**Comment by johan-bjareholt** [comment]
There is also a few risky unwraps in the period_union transform code.

**Comment by ErikBjare** [comment]
lol, woops!

Tested it out, seems to work great!
