### ISSUE TITLE
Support for rust stable

### ISSUE THREAD

**Issue by johan-bjareholt** [ActivityWatch/aw-server-rust#278]
- [x] rocket
    - Fixed in 0.5.0-rc1
- [ ] plex
    - [Needs proc_macro::Span stabilized](https://github.com/goffrie/plex/issues/13#issuecomment-591080125)

**Comment by hapm** [comment]
The client could theoretically be build on stable right now then, because it doesn't depend on aw-query, correct?

**Comment by johan-bjareholt** [comment]
@hapm Yes, that is correct!

**Comment by IamRezaMousavi** [comment]
Hello
I would like to contribute in this project
Why build workflow is failed?

**Comment by ErikBjare** [comment]
@IamRezaMousavi If you have a look you'll see that it's only failing for Android.

**Comment by huantianad** [comment]
@ErikBjare README should probably be updated to reflect the rust stable support too

**Comment by johan-bjareholt** [comment]
Thanks @huantianad, fixed in https://github.com/ActivityWatch/aw-server-rust/commit/01107b655de75642b20045fa18cdccb9cc04d4bd
