### ISSUE TITLE
Bitdefender quarantines aw-server-rust.exe v0.12.1

### ISSUE THREAD

**Issue by florianklumb** [ActivityWatch/aw-server-rust#321]
Although I installed Activity Watch v0.12.1 on Oct 8 already, today - maybe due to updated signatures - Bitdefender on Windows detected and quarantined the `aw-server-rust.exe` with this message:

> The file C:\Users\Florian Klumb\AppData\Local\Programs\ActivityWatch\aw-server-rust\aw-server-rust.exe is infected with Gen:Variant.Lazy.258757 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.

VirusTotal also flags it as malicious for two engines including Google (?): https://www.virustotal.com/gui/file/feffd45b4d8310ef15a743dc3445ad2d1e9ed8c1c69fb74c5dc1560ef721b6d9/detection

**Comment by ErikBjare** [comment]
Please see: https://github.com/ActivityWatch/activitywatch/issues/181
