### ISSUE TITLE
Bump rocket and rocket_cors

### ISSUE THREAD

**Issue by huantianad** [ActivityWatch/aw-server-rust#376]
`rocket_cors` recently released [0.6.0-alpha2](https://github.com/lawliet89/rocket_cors/commit/985098dd8f3b052716111eaa872d184cc21a1a68), with the unreleased patch that we used git to get previously. We should be able to bump both dependencies and remove the need for the git source.

PS the server version is one patch release behind :stuck_out_tongue:

**Comment by ErikBjare** [comment]
This has been fixed! Thanks for reporting :)
