### ISSUE TITLE
Cut events past starttime/endtime

### ISSUE THREAD

**Issue by johan-bjareholt** [ActivityWatch/aw-server-rust#38]
aw-server-rust storage is now inclusive about filtering events within a starttime+endtime, we need to cut the events which go outside of this filter.

**Comment by ErikBjare** [comment]
I think this should be toggleable with an argument to the endpoint (`trim`? `cut`?).

**Comment by johan-bjareholt** [comment]
In what possible scenario wouldn't you want this feature? I cannot see any use-case for that.

**Comment by johan-bjareholt** [comment]
Considering that we changed the start/end of day setting this is issue is less relevant.

I also realized that it could be an issue for example if someone gets events and in the future when we add support for manually editing events it could be an issue that the user mistakenly replaces the event with an event which is shorter by mistake. A corner-case, but an issue none the less.

**Comment by johan-bjareholt** [comment]
This is fixed, see get_events in src/datastore.rs in aw-datastore.
