### ISSUE TITLE
Running aw-client tests on aw-server-rust

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-server-rust#4]
This would be a neat because it would enable sharing of tests on the API level. Would be great for ensuring that communication between implementations is consistent.

Low priority though.

**Comment by ErikBjare** [comment]
Realized not that what we should be using is aw-client tests, not aw-server tests, since these would be integration-level.

**Comment by johan-bjareholt** [comment]
Was fixed when we moved aw-client-rust into the aw-server-rust repo I just realized, closing.
