### ISSUE TITLE
This is really a great project. I would like to help you with some functionalities. Please let me know where to start.

### ISSUE THREAD

**Issue by Doslin** [ActivityWatch/aw-server-rust#406]

**Comment by Doslin** [comment]
I have 2 years of experience in Rust development and 5 years of experience in golang development. I am Chinese 🇨🇳

I have been working in the field of big data real-time processing. Since my university days, I have enjoyed tinkering with software related to time recording. I hope I can help you with this project.
[aw-sync](https://github.com/ActivityWatch/aw-server-rust/tree/master/aw-sync)，[aw-leaderboard](https://github.com/ActivityWatch/aw-leaderboard) I would like to try both of the above

**Comment by ErikBjare** [comment]
Awesome. 

Given Chinese, could you join the Discord still? Or do you prefer another mode of communication?

**Comment by Doslin** [comment]
I use a proxy network, like you, to access freely.
I have joined [Discord](https://discord.com/channels/755040852727955476/782560139450384384/1146339299978133524)(xyzxy#0343). and I have DM'ed you.
