### ISSUE TITLE
OPTIONS route not generated for endpoints

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-server-rust#42]
I get this error when running aw-server-rust on Android together with aw-watcher-web on Firefox for Android:

```
D/aw-server-rust: Error: No matching routes for OPTIONS /api/0/buckets/aw-watcher-web-firefox/heartbeat?pulsetime=80.
D/aw-server-rust: Warning: Responding with 404 Not Found catcher.
```

Flask autogenerates the `OPTIONS` route for endpoints. I had hoped Rocket would do the same, but apparently not. Do we really implement `OPTIONS` routes on every endpoint? Hasn't anyone else had this issue before? (A quick search suggested no, but could be mistaken)

**Comment by johan-bjareholt** [comment]
rocket_cors should implement OPTIONS, maybe that's misconfigured somehow?

I have seen OPTIONS requests go through many times though, not sure how your scenario differs.

**Comment by ErikBjare** [comment]
That's weird, I just restarted the extension to checked that the same thing happens when creating a bucket, and it does:

```
D/aw-server-rust: Warning: Responding with 404 Not Found catcher.
D/aw-server-rust: Error: No matching routes for OPTIONS /api/0/buckets/aw-watcher-web-firefox.
```

**Comment by johan-bjareholt** [comment]
This is how it looks on my machine, the OPTIONS request gets a 204 and the HEARTBEAT afterwards a 200.

```
[2019-05-07][17:00:59][rocket::rocket][INFO] OPTIONS /api/0/buckets/aw-watcher-web-firefox/heartbeat?pulsetime=80:
[2019-05-07][17:00:59][_][INFO] Origin has a regex match? true
[2019-05-07][17:00:59][_][ERROR] No matching routes for OPTIONS /api/0/buckets/aw-watcher-web-firefox/heartbeat?pulsetime=80.
[2019-05-07][17:00:59][_][WARN] Responding with 404 Not Found catcher.
[2019-05-07][17:00:59][_][INFO] CORS Fairing: Turned missing route OPTIONS /api/0/buckets/aw-watcher-web-firefox/heartbeat?pulsetime=80 into an OPTIONS pre-flight request
[2019-05-07][17:00:59][_][INFO] Response succeeded.
```

**Comment by johan-bjareholt** [comment]
I just realized that the webextension UUID is different on all of my computers even though all of them run on the same version of the webextension from the Mozilla add-ons store.

So the issue for you is likely that the UUID is not in the allowed list in cors.rs so the CORS fairing is not catching the request. What we need to do is to do the same thing as in aw-server-python and allow all "moz-extension://" cors requests.

**Comment by johan-bjareholt** [comment]
Fixed by https://github.com/ActivityWatch/aw-watcher-web/pull/36

**Comment by johan-bjareholt** [comment]
It's still apparent, not sure why

**Comment by johan-bjareholt** [comment]
There is no bug, just an annoying error message. 

Upstream Rocket issue is https://github.com/SergioBenitez/Rocket/issues/1098

**Comment by patrolez** [comment]
As far as I was investigating, so:
1. https://github.com/SergioBenitez/Rocket/issues/25
2. Is being mitigated with: https://github.com/lawliet89/rocket_cors
    * but it has some issues https://github.com/lawliet89/rocket_cors/issues/76
