### ISSUE TITLE
Missing license file in mpsc_requests-0.3.3.crate

### ISSUE THREAD

**Issue by wojnilowicz** [ActivityWatch/aw-server-rust#480]
LICENSE is missing in mpsc_requests-0.3.3.crate downloaded from https://crates.io/crates/mpsc_requests. I would like to package it as a rpm for Fedora (which identifies missing license as a [mistake](https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/#_license_text) and encourages upstream to include it) and it would make it easier. Could you add the license file at
https://github.com/wojnilowicz/mpsc_requests/blob/add-license/LICENSE
to
https://github.com/johan-bjareholt/mpsc_requests
?
I cannot make a PR there, because the repository is already archived. Thanks for any help.

**Comment by ErikBjare** [comment]
@johan-bjareholt wrote this library. I thought we no longer used it, but looks like there are still references to it in aw-server-rust. I don't know why the repo was archived.

While I don't speak for Johan, I assume he'd release it under MIT (more permissive and suitable for a library than this than the MPL2, imo).

**Comment by wojnilowicz** [comment]
> @johan-bjareholt wrote this library. I thought we no longer used it, but looks like there are still references to it in aw-server-rust. I don't know why the repo was archived.
> 
> While I don't speak for Johan, I assume he'd release it under MIT (more permissive and suitable for a library than this than the MPL2, imo).

Ok. I got MPL2 from the metadata at https://crates.io/crates/mpsc_requests
Maybe it's good then to clarify it with @johan-bjareholt

**Comment by ErikBjare** [comment]
Strange. I just had a look in the [Cargo.toml](https://github.com/johan-bjareholt/mpsc_requests/blob/0bb3c4a8052d18c1cb36aacfe1c7f36a895678ef/Cargo.toml#L5), and there the license is `GPL-3.0-only`. Very confusing.

**Comment by wojnilowicz** [comment]
@ErikBjare I tried to contact @johan-bjareholt per e-mail on 2024-06-03 and 2024-06-20 but without any answer. Do you have any other means to contact him?

**Comment by ErikBjare** [comment]
He's on vacation, I will notify him when he's back.

**Comment by johan-bjareholt** [comment]
The version published in crates.io is actually not from my account, but from https://github.com/activitywatch/mpsc_requests so any ActivityWatch maintainer can merge that. That's also why the one on my account is archived. It seems though like I am the only owner on crates.io, so I have to publish any new versions.

**Comment by johan-bjareholt** [comment]
I have now fixed the license file and uploaded a version 0.3.4 version which includes it.

**Comment by wojnilowicz** [comment]
Thank you.
