### ISSUE TITLE
Flooding transform seems to be broken

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-server-rust#9]
I just took a glance at the flooding transform as @johan-bjareholt suggested in https://github.com/ActivityWatch/aw-core/pull/73 and I find several issues.

https://github.com/ActivityWatch/aw-server-rust/blob/b31fe9571f9f8c072ec0980879416ef9516e2928/src/transform/mod.rs#L61-L96

 - `gap` isn't calculated correctly (calculated as the difference between event starts, should be calculated as the difference between event1 end and event2 start)
 - Calculating gap correctly will lead to some events getting a negative gap, which in turn will lead to the same bug as the one fixed in https://github.com/ActivityWatch/aw-core/pull/73
 - Doesn't seem to prioritize flooding the larger event over the smaller event

No rush to fix, but the issue is there. Should be easier to rewrite now that the issues have been removed from aw-core-python.

**Comment by johan-bjareholt** [comment]
> Doesn't seem to prioritize flooding the larger event over the smaller event

This seems like an odd assumption, wouldn't the best solution be to meet half-way?

Anyways, this would be impossible to do currently since the peeked e2 is not mutable, I need to solve that somehow.

**Comment by ErikBjare** [comment]
It's not a big deal really, just how I formulated flooding when I made the spec. I made the assumption that the probability of the larger event actually occupying the gap is larger than the small event doing so.

Arguably just adds complexity with minimal value, but prevents a lot of small events from together becoming large after flooding.

**Comment by johan-bjareholt** [comment]
Fixed in #10
