### ISSUE TITLE
Consider using experimental feature NoneError

### ISSUE THREAD

**Issue by xylix** [ActivityWatch/aw-server-rust#90]
Something I realized while writing tests in aw-server/tests/api.rs was that if we had the [NoneError feature](https://doc.rust-lang.org/core/option/struct.NoneError.html ) we could use the ? operator instead of the bazillion unwrap calls to unwrap requests etc. It would also require the tests to return Result<(), None> type, but imo it would make them faster to write and a bit more readable.

I'm not sure if other places in our codebase could benefit from NoneError, and that might be the factor which makes it clear if we want it now or maybe we should just wait until the feature is stabilized.

Any opinions @ErikBjare @johan-bjareholt ?

**Comment by ErikBjare** [comment]
Never heard of it before. For tests, it sounds like a good idea to me, but I don't think I'd want this outside of tests. 

What about you @johan-bjareholt?

**Comment by johan-bjareholt** [comment]
Doesn't really matter to me whether we use 9 chars for ".unwrap()" or just a "?".
Don't really see it as much of a problem.

**Comment by xylix** [comment]
Fair. I think I also had an additional use case for returning NoneError's in mind when I wrote this, but I'll bring it up in the future if it's actually helpful.
