### ISSUE TITLE
Rarely failing datastore_reload in tests

### ISSUE THREAD

**Issue by xylix** [ActivityWatch/aw-server-rust#95]
`test datastore_tests::test_datastore_reload ... FAILED` fails maybe 1/30 - 1/50 test runs.

Failure trace:
```
---- datastore_tests::test_datastore_reload stdout----
thead 'datastore_tests::test_datastore_reload' panicked at 'assertion failed: `left == right`
left: `None`,
right: `Some(2020-03-06T08:31:16.342827937Z)`', at-datastore/tests/datastore.rs:423:13
```

Happened in my ubuntu VM when looping tests grepping for failures. Has also sometimes happened on my macOS, but I only saw it when I was adding the KV store so I thought it was related to some other failing tests back then.

**Comment by ErikBjare** [comment]
I've stumbled into this in CI now as well, see #101.

From that issue:

>This has happened to me a couple of times now, only in macOS builds (that I can remember): https://travis-ci.org/github/ActivityWatch/activitywatch/jobs/665409298
>
>I've been getting it with GitHub Actions as well, so not Travis-specific.

**Comment by johan-bjareholt** [comment]
It might be that the first datastore created in that test does not commit before it quits? Maybe we just need to call force_commit on the datastore before quitting? Or even better, maybe we should force a commit when the datastore starts up?

This is just a guess though, I'm not exactly sure how SQLite transactions behave. I have set the transaction drop behavior before to "Commit" in the hopes for it to commit by default when the server is suddenly shut down, but maybe this doesn't work as I expected.

**Comment by johan-bjareholt** [comment]
Lol, I wrote "Might fix" in the PR and GitHub only understood the word "fix".

Reopening, if no one sees it for a while we can close it.

**Comment by johan-bjareholt** [comment]
Seems to not be an issue anymore, closing. Feel free to open it again if it occurs again.
